<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport"
    content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <title>Document</title>
</head>

<body>
  <?php
  $rawApiResponse = file_get_contents('https://dog.ceo/api/breeds/image/random');
  $apiResponse = json_decode($rawApiResponse, true);


  ?>

  <img src="<?= $apiResponse["message"] ?>" alt="">
</body>

</html>